baseURL = "https://technicalwealth.ee/"
languageCode = "en-us"
title = "Technical Wealth"
author = "Karl-Aksel Puulmann"
theme = "hugo-vitae"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  # Add meta keywords in head part (Site Keywords or Tags of Page)
  keywords = ["software", "blog"]

  # Add meta description in head part
  description = "Vitae is a blog theme for Hugo that focuses on your content."

  # Add pagetitle to homepage <title> tag
  #pagetitle = "All about static site generation"

  # Add a subtitle to your website
  subtitle = "Blog for Karl-Aksel Puulmann"

  # Activate to show authors on pages if available
  listAuthor = true

  # Add math typesetting with KaTeX (Global with this Param)
  math = true

  # Add list of sections that should show up on the homepage
  mainSections = ["posts"]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2

[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/macobo"

[[params.social]]
name = "Linkedin"
icon = "fab fa-linkedin"
url = "https://www.linkedin.com/in/karlakselpuulmann/"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"
