baseURL = "https://technicalwealth.ee/"
languageCode = "en-us"
title = "Karl-Aksel Puulmann"
theme = "hugo-vitae"

[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/macobo"
